# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Code Check

on:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 --filename=./src/RandomMath/*.py --count --statistics
        flake8 --filename=./src/RandomMath/*.py --count --statistics --exit-zero --max-complexity=10 --max-line-length=127
        flake8 --filename=./test/RandomMath/*.py --count --statistics
        flake8 --filename=./test/RandomMath/*.py --count --statistics --exit-zero --max-complexity=10 --max-line-length=127
    - name: Test with pytest
      run: |
        pytest test/RandomMath