# Publish Python Package to Pypi

name: Package Prerelease

on:
  release:
    types:
      [prereleased]

jobs:
  
  publish:
    uses: ./.github/workflows/2_1-publish-prerelease.yml
    secrets: inherit