# Publish Python Package to Pypi

name: Package Prerelease

on:
  release:
    types:
      [prereleased]

jobs:
  
  publish:
    uses: ./.github/workflows/2_1-publish-prerelease.yml
    with:
      tag_name: ${{ github.event.release.tag_name }}
    secrets: inherit