# Publish Python Package to Pypi

name: Package Release

on:
  release:
    types:
      [released]

jobs:
  
  publish:
    uses: ./.github/workflows/2_1-publish-release.yml
    with:
      tag_name: ${{ github.event.release.tag_name }}
    secrets: inherit