# Publish Python Package to Pypi

name: Package Prerelease

on:
  release:
    types: [released]

jobs:
  
  publish:
    uses: ./.github/workflows/publish-prerelease.yml
    with:
      tag_name: ${{ github.event.release.tag_name }}
    secrets: inherit