# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Publish on Pypi

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  
  publish:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check release
        run: |
          echo ${{ inputs.tag_name }}
      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          regex: true
          file: "random_math.*"
          target: "dist/"
          version: tags/${{ inputs.tag_name }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{secrets.PYPI_API_TOKEN}}
          skip_existing: true