name: Deploy to Render

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Render  
        run: |
          curl -X POST ${{ secrets.RENDER_WEBHOOK_URL }}