
name: Publish on Pypi

on:
  release:
    types: [released]

jobs:
  
  publish:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check release
        run: |
          echo ${{ github.event.release.tag_name }}
      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          regex: true
          file: "RandomMath.*"
          target: "dist/"
          version: tags/${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to TestPyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{secrets.PYPI_API_TOKEN}}
          skip_existing: true