# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Publish Python Package

on:
  workflow_run:
    workflows: [Python Package CI]
    types: [completed]
    branches:
      - '*'

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create Dist
      run: |
        python -m build
    - name: Check Tag Type
        id: tagtype
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+[ab][0-9]+$ ]]; then
              echo ::set-output name=type::pre
          fi
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=type::release
          fi
      - name: Publish PreRelease
        if: steps.tagtype.outputs.type == 'pre'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          generateReleaseNotes: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          prerelease: true
      - name: Publish Release
        if: steps.tagtype.outputs.type == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          generateReleaseNotes: true
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          prerelease: false
      
