# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Package CI

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
    tags: v*
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.pithon.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 --filename=./src/complexoperations/*.py --count --statistics
        flake8 --filename=./src/complexoperations/*.py --count --statistics --exit-zero --max-complexity=10 --max-line-length=127
        flake8 --filename=./test/complexoperations/*.py --count --statistics
        flake8 --filename=./test/complexoperations/*.py --count --statistics --exit-zero --max-complexity=10 --max-line-length=127
    - name: Test with pytest
      run: |
        pytest

  prerelease:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
        with:
          python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi    
    - name: Create Dist
      run: |
        python -m build
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"
        generateReleaseNotes: true
        token: ${{ secrets.MY_TOKEN }}
          prerelease: true
